Homework nr 8
Atem89/BORTNIC_EUGENIU pull request #8
Opened 2024-04-12 07:03 UTC by Atem89

2024-04-15 17:46 UTC, gh3rtzz commented on src/main/java/homework_nr_8/NoDuplicate.java
> +        for (String i : list) {
This works but makes no sense. You could've used List here and get the same result. Try to: Set<String> set = new HashSet<>(duplicates);

2024-04-15 17:47 UTC, gh3rtzz requested changes
comment

2024-04-15 21:35 UTC, Atem89 commented on src/main/java/homework_nr_8/NoDuplicate.java
> +        for (String i : list) {
Thank you.

2024-04-19 07:41 UTC, gh3rtzz commented on src/main/java/homework_nr_8/NoDuplicate.java
> +        for (String i : list) {
now remove the for loop below, you don't need it anymore

2024-04-19 08:50 UTC, Atem89 commented on src/main/java/homework_nr_8/NoDuplicate.java
> +        for (String i : list) {
Thank you.

2024-04-22 17:30 UTC, gh3rtzz approved these changes
approved

2024-04-22 17:51 UTC, merged